apiVersion: v1
kind: ConfigMap
metadata:
  name: vendure-config
  namespace: simket
  labels:
    app.kubernetes.io/name: vendure-config
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: simket
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "vendure"
  REDIS_CACHE_HOST: "redis-cache"
  REDIS_CACHE_PORT: "6379"
  REDIS_QUEUE_HOST: "redis-queue"
  REDIS_QUEUE_PORT: "6379"
  TYPESENSE_HOST: "typesense"
  TYPESENSE_PORT: "8108"
  QDRANT_HOST: "qdrant"
  QDRANT_PORT: "6334"
  CLAMAV_HOST: "clamav"
  CLAMAV_PORT: "3310"
  VENDURE_PORT: "3000"
  NODE_ENV: "production"
